baseurl = "https://geoheil.github.io/"
languageCode = "en-us"
title = "geoHeil"
theme = "hugo-type-theme"
# Enable comments by entering your Disqus shortname
disqusShortname = "geoheil"
# Add your tracking code to enable Google Analytics
googleAnalytics = "UA-83207234-1"
# Posts per page
paginate = 3


[params]
	author = "geoHeil"
	description = "Add a description of your website"
	# The keywords will be added as a meta tag. Delimit them with a comma.
	keywords = "data science, forecasting, big data, spark, scala"
	# Either show custom avatar on the top
	# left by adding the filename in below
	avatar = "img/avatar.png"
	# or use Gravatar by adding your email address to generate a unique avatar
	gravatar = "georg.kf.heiler@gmail.com"

	headerText = "data science | needn't be rocket science.<br><br>a grad student's blog about data analytics and related topics."
	# To add a header background to the main site, save your image under static/img/.
	# If now image path is provided, a orange background will be shown instead.
	headerImage = ""
	copyright = "[geoHeil](//github.com/geoHeil) <br>Powered by [Hugo](//gohugo.io/) with the [Type Theme](//github.com/digitalcraftsman/hugo-type-theme)"


	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = false
		homepage = false
		email = "georg.kf.heiler@gmail.com"
		behance = ""
		bitbucket  =""
		dribbble = ""
		facebook = ""
		flickr = ""
		github = "geoheil"
		googleplus = ""
		instagram = ""
		linkedin = "https://at.linkedin.com/in/georg-heiler-019b3767"
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = "http://stackexchange.com/users/1706292/"
		steam = ""
		tumblr = ""
		twitter = ""
		wordpress = ""
		youtube = ""
